### ISSUE TITLE
Gekko: "I do not know the indicator ADX"

### ISSUE THREAD

**Issue by xerviami** [tommiehansen/gekko_tools#1]
Hi,

First of all, thank you for sharing your strategies !

Gekko tells me "I do not know the indicator ADX" even if I installed Tulind.
I looked inside the strategy and adx is declared with: 
this.addIndicator('maFast', 'SMA', this.settings.SMA_short );

According to the gekko doc, it should use "this.addTulipIndicator", no ?

thank you very much for your work :-)
Xavier

**Comment by tommiehansen** [comment]
Last updated version using ADX does not use the ADX-indicator from the Tulip library but instead uses a custom made version by user @gab0.

Please see the the forum thread about these strategies:
https://forum.gekko.wizb.it/thread-100.html

And read under 'Instructions for use'

Good luck!

**Comment by xerviami** [comment]
Hi,
Thank you Tommie for your answer.
It works with the adx version of @Gab0.
Xavier
