### ISSUE TITLE
Error while loading ADX indicator

### ISSUE THREAD

**Issue by starsaillor** [tommiehansen/gekko_tools#4]
First of all, thank you for your effort and for sharing your strategy. 

I decided to give it a try today, after following all the instructions in https://forum.gekko.wizb.it/thread-100.html, I went on to do some backtesting. 

I got an error related to the ADX indicator, I got the file from user Gab0. https://imgur.com/a/9NWPwSe

Any ideas? Have I done something wrong?

Thanks again

**Comment by starsaillor** [comment]
Anyone?

**Comment by jnikles** [comment]
You need extra indicators in strategies/indicators. Copy these over, and you're good to go: https://github.com/Gab0/gekko-extra-indicators
